-- ==========================================
-- SAKLI TERAPI - Email notification delivery
-- Migration 013
-- ==========================================
-- Run this after Migration 012. Operational email is opt-in. Authentication
-- emails (confirmation and password recovery) continue to be sent by Supabase.

BEGIN;

CREATE TABLE IF NOT EXISTS public.notification_preferences (
  user_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  email_session_updates boolean NOT NULL DEFAULT false,
  email_review_updates boolean NOT NULL DEFAULT false,
  email_account_updates boolean NOT NULL DEFAULT false,
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

INSERT INTO public.notification_preferences (user_id)
SELECT id FROM public.profiles
ON CONFLICT (user_id) DO NOTHING;

ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notification_preferences_select_own"
  ON public.notification_preferences;
DROP POLICY IF EXISTS "notification_preferences_update_own"
  ON public.notification_preferences;

CREATE POLICY "notification_preferences_select_own"
  ON public.notification_preferences FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "notification_preferences_update_own"
  ON public.notification_preferences FOR UPDATE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

REVOKE ALL ON TABLE public.notification_preferences FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.notification_preferences TO authenticated;
GRANT UPDATE (
  email_session_updates,
  email_review_updates,
  email_account_updates
) ON TABLE public.notification_preferences TO authenticated;

CREATE OR REPLACE FUNCTION private.touch_notification_preferences()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.touch_notification_preferences()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trigger_touch_notification_preferences
  ON public.notification_preferences;
CREATE TRIGGER trigger_touch_notification_preferences
BEFORE UPDATE ON public.notification_preferences
FOR EACH ROW
EXECUTE FUNCTION private.touch_notification_preferences();

CREATE OR REPLACE FUNCTION private.create_notification_preferences()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.notification_preferences (user_id)
  VALUES (NEW.id)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.create_notification_preferences()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trigger_create_notification_preferences
  ON public.profiles;
CREATE TRIGGER trigger_create_notification_preferences
AFTER INSERT ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION private.create_notification_preferences();

CREATE TABLE IF NOT EXISTS public.email_notification_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id uuid NOT NULL UNIQUE
    REFERENCES public.notifications(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  category text NOT NULL CHECK (category IN ('session', 'review', 'account')),
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'sent', 'failed')),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  available_at timestamp with time zone NOT NULL DEFAULT now(),
  last_error text,
  sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_notification_outbox_pending
  ON public.email_notification_outbox(available_at, created_at)
  WHERE status IN ('pending', 'failed', 'processing');

ALTER TABLE public.email_notification_outbox ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.email_notification_outbox FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION private.create_notification(
  target_user_id uuid,
  notification_type text,
  notification_title text,
  notification_message text,
  notification_action_url text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  created_notification_id uuid;
  notification_category text;
  email_enabled boolean := false;
BEGIN
  IF target_user_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = target_user_id
  ) THEN
    RETURN;
  END IF;

  INSERT INTO public.notifications (user_id, type, title, message, action_url)
  VALUES (
    target_user_id,
    pg_catalog.left(pg_catalog.btrim(notification_type), 64),
    pg_catalog.left(pg_catalog.btrim(notification_title), 120),
    pg_catalog.left(pg_catalog.btrim(notification_message), 500),
    CASE
      WHEN notification_action_url LIKE '/%'
       AND notification_action_url NOT LIKE '//%'
      THEN notification_action_url
      ELSE NULL
    END
  )
  RETURNING id INTO created_notification_id;

  notification_category := CASE
    WHEN notification_type LIKE 'session_%' THEN 'session'
    WHEN notification_type LIKE 'psychologist_%' THEN 'review'
    ELSE 'account'
  END;

  SELECT CASE notification_category
    WHEN 'session' THEN preferences.email_session_updates
    WHEN 'review' THEN preferences.email_review_updates
    ELSE preferences.email_account_updates
  END
  INTO email_enabled
  FROM public.notification_preferences AS preferences
  WHERE preferences.user_id = target_user_id;

  IF COALESCE(email_enabled, false) THEN
    INSERT INTO public.email_notification_outbox (
      notification_id,
      user_id,
      category
    )
    VALUES (
      created_notification_id,
      target_user_id,
      notification_category
    )
    ON CONFLICT (notification_id) DO NOTHING;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION private.create_notification(uuid, text, text, text, text)
  FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.claim_email_notification_batch(batch_size integer DEFAULT 20)
RETURNS TABLE (
  queue_id bigint,
  recipient_email text,
  notification_title text,
  notification_message text,
  notification_action_url text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  RETURN QUERY
  WITH candidates AS (
    SELECT outbox.id
    FROM public.email_notification_outbox AS outbox
    WHERE outbox.attempt_count < 5
      AND outbox.available_at <= now()
      AND (
        outbox.status IN ('pending', 'failed')
        OR (
          outbox.status = 'processing'
          AND outbox.updated_at < now() - interval '15 minutes'
        )
      )
    ORDER BY outbox.created_at
    FOR UPDATE SKIP LOCKED
    LIMIT LEAST(GREATEST(COALESCE(batch_size, 20), 1), 50)
  ), claimed AS (
    UPDATE public.email_notification_outbox AS outbox
    SET
      status = 'processing',
      attempt_count = outbox.attempt_count + 1,
      last_error = NULL,
      updated_at = now()
    FROM candidates
    WHERE outbox.id = candidates.id
    RETURNING outbox.id, outbox.notification_id, outbox.user_id
  )
  SELECT
    claimed.id,
    profiles.email,
    notifications.title,
    notifications.message,
    notifications.action_url
  FROM claimed
  JOIN public.profiles AS profiles ON profiles.id = claimed.user_id
  JOIN public.notifications AS notifications ON notifications.id = claimed.notification_id;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_email_notification_batch(integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_email_notification_batch(integer)
  TO service_role;

CREATE OR REPLACE FUNCTION public.complete_email_notification(
  p_queue_id bigint,
  p_was_sent boolean,
  p_failure_message text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.email_notification_outbox
  SET
    status = CASE WHEN p_was_sent THEN 'sent' ELSE 'failed' END,
    sent_at = CASE WHEN p_was_sent THEN now() ELSE NULL END,
    last_error = CASE
      WHEN p_was_sent THEN NULL
      ELSE pg_catalog.left(COALESCE(p_failure_message, 'unknown delivery error'), 500)
    END,
    available_at = CASE
      WHEN p_was_sent THEN available_at
      WHEN attempt_count <= 1 THEN now() + interval '1 minute'
      WHEN attempt_count = 2 THEN now() + interval '5 minutes'
      WHEN attempt_count = 3 THEN now() + interval '15 minutes'
      ELSE now() + interval '1 hour'
    END,
    updated_at = now()
  WHERE id = p_queue_id
    AND status = 'processing';
END;
$$;

REVOKE ALL ON FUNCTION public.complete_email_notification(bigint, boolean, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.complete_email_notification(bigint, boolean, text)
  TO service_role;

COMMIT;
