-- ==========================================
-- SAKLI TERAPI - Notifications and operations
-- Migration 012
-- ==========================================
-- Run this after Migration 011. This migration adds private, persistent
-- in-app notifications and an auditable psychologist review workflow.

BEGIN;

ALTER TABLE public.psychologists
  ADD COLUMN IF NOT EXISTS review_reason text,
  ADD COLUMN IF NOT EXISTS reviewed_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS reviewed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.psychologists
  DROP CONSTRAINT IF EXISTS psychologists_approval_status_check;
ALTER TABLE public.psychologists
  ADD CONSTRAINT psychologists_approval_status_check
  CHECK (approval_status IN ('pending', 'approved', 'rejected', 'suspended'));

CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid PRIMARY KEY DEFAULT pg_catalog.gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (char_length(type) BETWEEN 1 AND 64),
  title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 120),
  message text NOT NULL CHECK (char_length(message) BETWEEN 1 AND 500),
  action_url text CHECK (
    action_url IS NULL
    OR (action_url LIKE '/%' AND action_url NOT LIKE '//%')
  ),
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_created
  ON public.notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
  ON public.notifications(user_id, created_at DESC)
  WHERE read_at IS NULL;

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notifications_select_own" ON public.notifications;
DROP POLICY IF EXISTS "notifications_update_own" ON public.notifications;

CREATE POLICY "notifications_select_own"
  ON public.notifications FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "notifications_update_own"
  ON public.notifications FOR UPDATE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

REVOKE ALL ON TABLE public.notifications FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.notifications TO authenticated;
GRANT UPDATE (read_at) ON TABLE public.notifications TO authenticated;

CREATE TABLE IF NOT EXISTS public.admin_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  psychologist_id uuid REFERENCES public.psychologists(id) ON DELETE SET NULL,
  action text NOT NULL CHECK (char_length(action) BETWEEN 1 AND 64),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created
  ON public.admin_audit_log(created_at DESC);

ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_audit_log_select_admin" ON public.admin_audit_log;
CREATE POLICY "admin_audit_log_select_admin"
  ON public.admin_audit_log FOR SELECT
  TO authenticated
  USING ((SELECT private.is_admin_user()));

REVOKE ALL ON TABLE public.admin_audit_log FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.admin_audit_log TO authenticated;

CREATE OR REPLACE FUNCTION private.create_notification(
  target_user_id uuid,
  notification_type text,
  notification_title text,
  notification_message text,
  notification_action_url text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF target_user_id IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = target_user_id
  ) THEN
    RETURN;
  END IF;

  INSERT INTO public.notifications (user_id, type, title, message, action_url)
  VALUES (
    target_user_id,
    pg_catalog.left(pg_catalog.btrim(notification_type), 64),
    pg_catalog.left(pg_catalog.btrim(notification_title), 120),
    pg_catalog.left(pg_catalog.btrim(notification_message), 500),
    CASE
      WHEN notification_action_url LIKE '/%'
       AND notification_action_url NOT LIKE '//%'
      THEN notification_action_url
      ELSE NULL
    END
  );
END;
$$;

REVOKE ALL ON FUNCTION private.create_notification(uuid, text, text, text, text)
  FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION private.prepare_psychologist_review()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  actor_id uuid := (SELECT auth.uid());
BEGIN
  IF NEW.approval_status IS DISTINCT FROM OLD.approval_status THEN
    IF actor_id IS NOT NULL AND NOT (SELECT private.is_admin_user()) THEN
      RAISE EXCEPTION 'only admins can review psychologist applications'
        USING ERRCODE = '42501';
    END IF;

    IF NEW.approval_status IN ('rejected', 'suspended')
       AND NULLIF(pg_catalog.btrim(NEW.review_reason), '') IS NULL THEN
      RAISE EXCEPTION 'a review reason is required'
        USING ERRCODE = '22023';
    END IF;

    NEW.review_reason := CASE
      WHEN NEW.approval_status = 'approved' THEN NULL
      ELSE pg_catalog.left(NULLIF(pg_catalog.btrim(NEW.review_reason), ''), 500)
    END;
    NEW.reviewed_at := now();
    NEW.reviewed_by := actor_id;
  ELSIF actor_id IS NOT NULL
        AND NOT (SELECT private.is_admin_user())
        AND (
          NEW.review_reason IS DISTINCT FROM OLD.review_reason
          OR NEW.reviewed_at IS DISTINCT FROM OLD.reviewed_at
          OR NEW.reviewed_by IS DISTINCT FROM OLD.reviewed_by
        ) THEN
    RAISE EXCEPTION 'psychologist review fields are server-managed'
      USING ERRCODE = '42501';
  END IF;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.prepare_psychologist_review()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trigger_prepare_psychologist_review
  ON public.psychologists;
CREATE TRIGGER trigger_prepare_psychologist_review
BEFORE UPDATE ON public.psychologists
FOR EACH ROW
EXECUTE FUNCTION private.prepare_psychologist_review();

CREATE OR REPLACE FUNCTION private.record_psychologist_review()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  notification_title text;
  notification_message text;
BEGIN
  IF NEW.approval_status IS NOT DISTINCT FROM OLD.approval_status THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.admin_audit_log (
    actor_id,
    psychologist_id,
    action,
    metadata
  )
  VALUES (
    (SELECT auth.uid()),
    NEW.id,
    'psychologist_' || NEW.approval_status,
    pg_catalog.jsonb_build_object(
      'display_name', NEW.display_name,
      'previous_status', OLD.approval_status,
      'new_status', NEW.approval_status,
      'reason', NEW.review_reason
    )
  );

  notification_title := CASE NEW.approval_status
    WHEN 'approved' THEN 'Başvurunuz onaylandı'
    WHEN 'rejected' THEN 'Başvurunuz sonuçlandı'
    WHEN 'suspended' THEN 'Hesabınız askıya alındı'
    ELSE 'Başvuru durumunuz güncellendi'
  END;

  notification_message := CASE NEW.approval_status
    WHEN 'approved' THEN 'Psikolog profiliniz onaylandı ve platformda görünür hale geldi.'
    WHEN 'rejected' THEN 'Başvurunuz incelendi. Ayrıntıları psikolog panelinizden görebilirsiniz.'
    WHEN 'suspended' THEN 'Profiliniz geçici olarak katalogdan kaldırıldı. Ayrıntıları panelinizden görebilirsiniz.'
    ELSE 'Başvurunuzun durumu güncellendi.'
  END;

  PERFORM private.create_notification(
    NEW.id,
    'psychologist_' || NEW.approval_status,
    notification_title,
    notification_message,
    '/psikolog-panel'
  );

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.record_psychologist_review()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trigger_record_psychologist_review
  ON public.psychologists;
CREATE TRIGGER trigger_record_psychologist_review
AFTER UPDATE ON public.psychologists
FOR EACH ROW
EXECUTE FUNCTION private.record_psychologist_review();

CREATE OR REPLACE FUNCTION private.notify_session_participants()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  schedule_text text;
  status_text text;
BEGIN
  schedule_text := pg_catalog.to_char(NEW.scheduled_date, 'DD.MM.YYYY')
    || ' ' || pg_catalog.left(NEW.scheduled_time, 5);

  IF TG_OP = 'INSERT' THEN
    PERFORM private.create_notification(
      NEW.client_id,
      'session_created',
      'Randevunuz oluşturuldu',
      NEW.psychologist_name || ' ile ' || schedule_text || ' randevunuz oluşturuldu.',
      '/panel'
    );
    PERFORM private.create_notification(
      NEW.psychologist_id,
      'session_created',
      'Yeni randevu',
      schedule_text || ' için yeni bir randevu oluşturuldu.',
      '/psikolog-panel'
    );
  ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
    status_text := CASE NEW.status
      WHEN 'confirmed' THEN 'onaylandı'
      WHEN 'completed' THEN 'tamamlandı'
      WHEN 'cancelled' THEN 'iptal edildi'
      ELSE 'güncellendi'
    END;

    PERFORM private.create_notification(
      NEW.client_id,
      'session_status',
      'Randevu durumu güncellendi',
      schedule_text || ' tarihli randevunuz ' || status_text || '.',
      '/panel'
    );
    PERFORM private.create_notification(
      NEW.psychologist_id,
      'session_status',
      'Randevu durumu güncellendi',
      schedule_text || ' tarihli randevu ' || status_text || '.',
      '/psikolog-panel'
    );
  END IF;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.notify_session_participants()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trigger_notify_session_participants
  ON public.sessions;
CREATE TRIGGER trigger_notify_session_participants
AFTER INSERT OR UPDATE ON public.sessions
FOR EACH ROW
EXECUTE FUNCTION private.notify_session_participants();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_catalog.pg_publication WHERE pubname = 'supabase_realtime'
  ) AND NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'notifications'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
  END IF;
END
$$;

COMMIT;
