version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Istanbul
    open-pull-requests-limit: 5
    groups:
      react-runtime:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - patch
          - minor
      npm-patch-and-minor:
        exclude-patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
